### ISSUE TITLE
Diff in markdown-friendly format

### ISSUE THREAD

**Issue by am11** [madskristensen/FileDiffer#12]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 2
- This extension: 1.3
### Description

In addition to plain diff view, it would be handy to have the capability to view the diff in markdown-friendly git/gist-able format (with `+` and `-` signs).

This will make the diff readily shareable on git or gist (e.g. with `diff` language tag in markdown).

``` diff
- TODO: display hello world
+ Display( "Hello World" )
```

**Comment by madskristensen** [comment]
While that would be cool, it is not something this extension can provide. It has to be added to the VS diff viewer and [UserVoice](https://visualstudio.uservoice.com) is the best place to ask for that feature
