### ISSUE TITLE
Cannot make changes to either file while comparing them.

### ISSUE THREAD

**Issue by tomservaux** [madskristensen/FileDiffer#17]
I'm not sure whether this is a bug or not but I am trying to compare two files from different projects that contain similar code so that I can copy features between them. Unfortunately the editors are read only while I am comparing the files. Is this by design or is it just not implemented yet?

**Comment by madskristensen** [comment]
This is up to the individual language services (C#, HTML, XAML etc.) to enable editing in diff mode. However, I think they can only make the right side editable whereas the left is always read-only. There is nothing this extension can do to change that behavior, unfortunately.
