### ISSUE TITLE
When comparing with external file, show the path (full or ellipsed) of the external file and the name of the local file.

### ISSUE THREAD

**Issue by paulomorgado** [madskristensen/FileDiffer#18]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.4.24
### Description
When comparing with external file, show the path (full or ellipsed) of the external file and the name of the local file.

### Steps to recreate
1. Select a file in solution explorer
2. Select another file in the file open dialog

### Current behavior
The solution file will be on the left pane with the name **FileName - copy.cs** and the external file in the right pane with the name **FileName.cs**.

### Expected behavior
Like when comparing a file with one of its source control versions, the solution file should be on the right pane with its name unmodified and the first top combo box showing the project it belongs to and the external file should be on the left pane.

**Comment by madskristensen** [comment]
Unfortunately, that is not up to this extension to control. That's handled by Visual Studio's diffing tool
