### ISSUE TITLE
Extension loses right click context menu on restarting VS

### ISSUE THREAD

**Issue by erik3355** [madskristensen/FileDiffer#21]
### Installed product versions
- Visual Studio: 2015 community 
- This extension: 1.4.24

### Description
After installing the extension and restarting VS it works fine. When i close down VS and open it another time, the option in the right click context menu is gone. When going to extensions, the extension is still there and it has to be uninstalled and installed again for it to work again.

### Steps to recreate
1. install
2. close VS
3. open VS
4. close VS
5. open VS

### Current behavior
right click context menu to compare files dissappears

### Expected behavior
n.a.

**Comment by madskristensen** [comment]
Fixed
