### ISSUE TITLE
Doesn't seem to work in VS2019 

### ISSUE THREAD

**Issue by benmccallum** [madskristensen/FileDiffer#24]
### Installed product versions
- Visual Studio: 
-- Microsoft Visual Studio Community 2019
-- Version 16.0.1
-- VisualStudio.16.Release/16.0.1+28803.156
- This extension: 1.4.25

### Description
Right-clicking a file in sln explr and choosing "Compare Files..."

### Steps to recreate
1. Load sln
2. Right-click a file in sln explr and choose "Compare Files..."

### Current vs Expected behavior
Seems to open a File Dialog, whereas I'd expect it does nothing and then lets me choose the next file to compare against.

**Comment by benmccallum** [comment]
Oh man, silly me, tried again and if I select a different file the the File Dialog it compares them, which makes sense. 

Typical usage would seem to be Ctrl + file1, Ctrl + file2, right-click + compare files. 

I've used this extension before, but I think what's happened is I got used to an extension in VS Code that let's you right-click file1 + compare, right-click file2 + compare.

I wonder if it's worth supporting that via another menu option that starts as "Compare as left file..." and then when you right-click the next file a "Compare as right file..." menu option appears too. Would you be open to that?

**Comment by Trevor89** [comment]
![image](https://user-images.githubusercontent.com/46264947/79359180-2becee80-7f3a-11ea-9af7-6b166b98c92f.png)
I do not see compare files in vs2019 
![image](https://user-images.githubusercontent.com/46264947/79359258-47f09000-7f3a-11ea-9983-209060e843e5.png)

I tried selecting 2 files and 1 file as mentioned by benmccallum but neither option shows compare files

Trev

**Comment by madskristensen** [comment]
I just uploaded a new version. This shoudl be fixed now
