### ISSUE TITLE
Release notes link broken - 404

### ISSUE THREAD

**Issue by marcinsmialek** [madskristensen/FileDiffer#28]
### Installed product versions
- Visual Studio: 2022 Professional 17.3, but it shouldn't matter
- This extension: 2.0.28, but it shouldn't matter

### Description
The Release Notes links from the VS Extension Manager and info page on VS Marketplace lead to 404 page

### Steps to recreate
1. Open VS Extension Manager -> Marketplace
2. Find File Differ
3. Click "Release Notes"
4. GitHub 404 page is displayed

#### Another way - from site
1. Open [VS Marketplace page for File Differ](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileDiffer)
2. Click changelog link
3. GitHub 404 page is displayed

### Current behavior
Changelog link doesn't lead to changelog, but 404

### Expected behavior
Changelog link should lead to changelog, or it should be removed, or any other reasonable non-404 solution

**Comment by madskristensen** [comment]
Fixed
