### ISSUE TITLE
Sadly not working

### ISSUE THREAD

**Issue by Bennik2000** [madskristensen/FileDiffer#8]
### Installed product versions
- Visual Studio: Community 2015 Update 2
- This extension: 1.0.1
### Description

Can select the files but not compare
### Steps to recreate
1. I don't know
### Current behavior

It is showing up a MessageBox telling a error. When i clicked "Compare Filed..."
![unbenannt_](https://cloud.githubusercontent.com/assets/8039939/14213863/74615ba0-f83a-11e5-9f9e-d818e915c51d.PNG)
### Expected behavior

it should open the diff view

**Comment by madskristensen** [comment]
what type of project do you have open? MVC, Winforms, Cordova, or...?

**Comment by Bennik2000** [comment]
It happens on all testet projects like WPF, VSIX, Xamarin Android App, ...

**Comment by Bennik2000** [comment]
I think that I know what the problem is: I am using Visual Studio 2015 Community. It could be that the "Tools.DiffFiles" command is not avaiable in the free version.

**Comment by ygrenier** [comment]
Here same problem on french install. Apparently "Tools.DiffFiles" is not available on my french installation. I find a "Fichier.Comparer" command (can be translated by "File.Compare") in the command window, but when I run it, I got a "not available" message. Tested on VS2013 Pro, VS2015 Pro, CS2015 Community. If I add the command in a Toolbar the commands are always disabled.

Apprently @Bennik2000 use a German version, me a French version, perhaps a localisation problem ?

**Comment by madskristensen** [comment]
I may have found a fix. Please help by verifying it by installing the latest CI build found here http://vsixgallery.com/extension/ea5c68d6-cdae-4e79-bd46-2a39e95bb256/

**Comment by Bennik2000** [comment]
Unfortunately on my german install it does not work. But another message is displayed: "Falscher Parameter. (Ausnahme von HRESULT: 0x80070057 (E_INVALIDARG))". It can be translated to "Wrong parameter. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))"

**Comment by ygrenier** [comment]
Same message on my french install "Paramètre incorrect. (Exception de HRESULT : 0x80070057 (E_INVALIDARG))".

**Comment by madskristensen** [comment]
Ok, I'll try something else. Thanks for helping

**Comment by madskristensen** [comment]
Ok, I'm now using the command GUID and Id instead of the command name. Please try version 1.1.8 here http://vsixgallery.com/extension/ea5c68d6-cdae-4e79-bd46-2a39e95bb256/

**Comment by ygrenier** [comment]
Yes it's work for me! 

Thanks.

**Comment by Bennik2000** [comment]
It works for me, too! Great!

Thank you

**Comment by madskristensen** [comment]
Awesome. I'll make a new release in a few minutes. Thanks for helping out troubleshooting this issue
