### ISSUE TITLE
Should not show up for 3 or more files.

### ISSUE THREAD

**Issue by SoonDead** [madskristensen/FileDiffer#9]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.1.5
### Description

The menu item should only show up in the context menu if no more than 2 files are selected. It would also be good to see an example on how to do this.
### Current behavior

Currently it diffs the first 2 selected files.
### Expected behavior

The menu item should only show up in the context menu if no more than 2 files are selected.

**Comment by madskristensen** [comment]
Thanks for the bug report. Please help verify the fix in the latest CI build found here http://vsixgallery.com/extension/ea5c68d6-cdae-4e79-bd46-2a39e95bb256/
